language: node_js
node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build
  - mkdir build
  - cp -rf dist build/
  - cp -f index.html build/

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: build
  repo: balthild/katex-physics
  target_branch: gh-pages
  name: Balthild
  email: ibalthild@gmail.com
  on:
    branch: master
# E: Build LifeCycle

branches:
  only:
    - master
